name: Rust Example

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: icepuma/rust-action@master
        with:
          args: cargo fmt --all && cargo test --workspace